services:
  frontend:
    build:
      context: ./frontend
    container_name: inkominiapp-frontend
    ports:
      - "80:80"
    networks:
      - internal

networks:
  internal:
    driver: bridge
